import numpy as np
import scipy
import matplotlib.pyplot as plt
import skimage

IMG = skimage.io.imread('hand.tiff')

canny_sigma1 = skimage.feature.canny(IMG, sigma=1, low_threshold=0.05, high_threshold=0.15)
canny_sigma2 = skimage.feature.canny(IMG, sigma=2, low_threshold=0.05, high_threshold=0.15)
canny_sigma3 = skimage.feature.canny(IMG, sigma=3, low_threshold=0.05, high_threshold=0.15)
canny_low1 = skimage.feature.canny(IMG, sigma=2, low_threshold=0.0001, high_threshold=0.1)
canny_low2 = skimage.feature.canny(IMG, sigma=2, low_threshold=0.001, high_threshold=0.1)
canny_low3 = skimage.feature.canny(IMG, sigma=2, low_threshold=0.01, high_threshold=0.1)
canny_high1 = skimage.feature.canny(IMG, sigma=2, low_threshold=0.01, high_threshold=0.1)
canny_high2 = skimage.feature.canny(IMG, sigma=2, low_threshold=0.01, high_threshold=1)
canny_high3 = skimage.feature.canny(IMG, sigma=2, low_threshold=0.01, high_threshold=10)

plt.figure(figsize=(15, 10))
plt.subplot(3, 3, 1)
plt.title('sigma=1, low=0.05, high=0.15')
plt.imshow(canny_sigma1, cmap='gray')
plt.axis('off')

plt.subplot(3, 3, 2)
plt.title('sigma=2, low=0.05, high=0.15')
plt.imshow(canny_sigma2, cmap='gray')
plt.axis('off')

plt.subplot(3, 3, 3)
plt.title('sigma=3, low=0.05, high=0.15')
plt.imshow(canny_sigma3, cmap='gray')
plt.axis('off')

plt.subplot(3, 3, 4)
plt.title('sigma=2, low=0.0001, high=0.1')
plt.imshow(canny_low1, cmap='gray')
plt.axis('off')

plt.subplot(3, 3, 5)
plt.title('sigma=2, low=0.001, high=0.1')
plt.imshow(canny_low2, cmap='gray')
plt.axis('off')

plt.subplot(3, 3, 6)
plt.title('sigma=2, low=0.01, high=0.1')
plt.imshow(canny_low3, cmap='gray')
plt.axis('off')

plt.subplot(3, 3, 7)
plt.title('sigma=2, low=0.01, high=0.1')
plt.imshow(canny_high1, cmap='gray')
plt.axis('off') 

plt.subplot(3, 3, 8)
plt.title('sigma=2, low=0.01, high=1')
plt.imshow(canny_high2, cmap='gray')
plt.axis('off')

plt.subplot(3, 3, 9)
plt.title('sigma=2, low=0.01, high=10')
plt.imshow(canny_high3, cmap='gray')
plt.axis('off')

plt.show()


#### corner_harris #####

IMG = skimage.io.imread('modelhouses.png')

# Harris responses with method="k"
harris_sigma1 = skimage.feature.corner_harris(IMG, method="k", sigma=1, k=0.04)
harris_sigma2 = skimage.feature.corner_harris(IMG, method="k", sigma=2, k=0.04)
harris_sigma3 = skimage.feature.corner_harris(IMG, method="k", sigma=5, k=0.04)
harris_k1 = skimage.feature.corner_harris(IMG, method="k", sigma=2, k=0.01)
harris_k2 = skimage.feature.corner_harris(IMG, method="k", sigma=2, k=0.04)
harris_k3 = skimage.feature.corner_harris(IMG, method="k", sigma=2, k=0.1)

# Harris responses with method="eps"
harris_eps1 = skimage.feature.corner_harris(IMG, method="eps", sigma=3, eps=0.0001)
harris_eps2 = skimage.feature.corner_harris(IMG, method="eps", sigma=3, eps=0.01)
harris_eps3 = skimage.feature.corner_harris(IMG, method="eps", sigma=3, eps=1)

plt.figure(figsize=(15, 10))
plt.subplot(2, 3, 1)
plt.title('method="k", sigma=1, k=0.04')
plt.imshow(harris_sigma1, cmap='gray')
plt.axis('off')

plt.subplot(2, 3, 2)
plt.title('method="k", sigma=2, k=0.04')
plt.imshow(harris_sigma2, cmap='gray')
plt.axis('off')

plt.subplot(2, 3, 3)
plt.title('method="k", sigma=5, k=0.04')
plt.imshow(harris_sigma3, cmap='gray')
plt.axis('off')

plt.subplot(2, 3, 4)
plt.title('method="k", sigma=2, k=0.01')
plt.imshow(harris_k1, cmap='gray')
plt.axis('off')

plt.subplot(2, 3, 5)
plt.title('method="k", sigma=2, k=0.04')
plt.imshow(harris_k2, cmap='gray')
plt.axis('off')

plt.subplot(2, 3, 6)
plt.title('method="k", sigma=2, k=0.1')
plt.imshow(harris_k3, cmap='gray')
plt.axis('off')

plt.show()

plt.figure(figsize=(15, 10))

plt.subplot(1, 3, 1)
plt.title('method="eps", sigma=3, eps=0.0001')
plt.imshow(harris_eps1, cmap='gray')
plt.axis('off')

plt.subplot(1, 3, 2)
plt.title('method="eps", sigma=3, eps=0.01')
plt.imshow(harris_eps2, cmap='gray')
plt.axis('off')

plt.subplot(1, 3, 3)
plt.title('method="eps", sigma=3, eps=1')
plt.imshow(harris_eps3, cmap='gray')
plt.axis('off')

plt.show()


"""
Write a Python function that finds Harris corners by finding local max-
ima in the feature map generated by the skimage.feature.corner_harris
function. To find the local maxima you can use the function
skimage.feature.corner_peaks
"""

def harries_corner_peaks(image: np.ndarray, method: str, sigma: float, k: float = 0.04, eps: float = 0.0001, top_corners: int = 250) -> np.ndarray:
    harris_response = skimage.feature.corner_harris(image, method=method, sigma=sigma, k=k, eps=eps)
    corners = skimage.feature.corner_peaks(harris_response, num_peaks=top_corners)
    return corners

peaks = harries_corner_peaks(IMG, method="k", sigma=1, k=0.04)
plt.figure(figsize=(10, 10))
plt.imshow(IMG, cmap='gray')
plt.scatter(peaks[:, 1], peaks[:, 0], marker='x', color='red')
plt.title('Harris Corners Detected with corner_peaks')
plt.axis('off')
plt.show()